"""Interactive schematic 3D visualization for the Cardan engineering tool.

The viewer uses Plotly for a deployment-friendly WebGL scene. It consumes the
renderer-independent kinematic scene generated by ``cardan_core`` and does not
reimplement Hooke-joint equations in the visualization layer.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping

import numpy as np
from numpy.typing import NDArray

import cardan_core as core

try:
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots
except ModuleNotFoundError:  # pragma: no cover - deployment fallback
    go = None
    make_subplots = None


VIEWER_API_VERSION = 2


@dataclass(frozen=True, slots=True)
class ViewerLabels:
    title: str = "Schematic 3D Cardan Kinematics"
    current: str = "Current"
    optimized: str = "Optimized"
    selected_current: str = "Current configuration"
    selected_optimized: str = "Optimized configuration"
    input_angle: str = "Input angle θ (deg)"
    speed_ratio: str = "Total speed ratio q"
    play: str = "Play"
    pause: str = "Pause"
    joint: str = "Joint"
    shaft: str = "Shaft"
    input_yoke: str = "Input yoke"
    output_yoke: str = "Output yoke"
    cross: str = "Cross"
    schematic_note: str = "Canonical planar schematic — not a general spatial CAD reconstruction"


_SHAFT_COLORS = ("#4E79A7", "#F28E2B", "#59A14F", "#B07AA1")
_INPUT_YOKE_COLOR = "#5DADE2"
_OUTPUT_YOKE_COLOR = "#F5B041"
_CROSS_COLOR = "#D5D8DC"
_JOINT_COLOR = "#F4D03F"
_CURRENT_COLOR = "#5DADE2"
_OPTIMIZED_COLOR = "#58D68D"
_SELECTED_COLOR = "#F4D03F"


def plotly_available() -> bool:
    """Return whether Plotly is installed in the runtime."""

    return go is not None and make_subplots is not None


def _line_coordinates(points: list[NDArray[np.float64] | None]) -> tuple[list[float | None], ...]:
    x_values: list[float | None] = []
    y_values: list[float | None] = []
    z_values: list[float | None] = []
    for point in points:
        if point is None:
            x_values.append(None)
            y_values.append(None)
            z_values.append(None)
        else:
            values = np.asarray(point, dtype=float)
            x_values.append(float(values[0]))
            y_values.append(float(values[1]))
            z_values.append(float(values[2]))
    return x_values, y_values, z_values


def _yoke_points(
    center: NDArray[np.float64],
    direction: NDArray[np.float64],
    bearing_axis: NDArray[np.float64],
    side_sign: float,
) -> tuple[list[float | None], list[float | None], list[float | None]]:
    """Return a compact U-shaped yoke wireframe."""

    hub_distance = 0.43
    near_distance = 0.09
    half_span = 0.35
    direction = np.asarray(direction, dtype=float)
    bearing_axis = np.asarray(bearing_axis, dtype=float)
    hub_center = center + side_sign * hub_distance * direction
    near_center = center + side_sign * near_distance * direction

    hub_plus = hub_center + half_span * bearing_axis
    hub_minus = hub_center - half_span * bearing_axis
    near_plus = near_center + half_span * bearing_axis
    near_minus = near_center - half_span * bearing_axis

    return _line_coordinates([
        hub_minus, near_minus, None,
        hub_plus, near_plus, None,
        hub_minus, hub_plus,
    ])


def _cross_points(
    center: NDArray[np.float64],
    input_axis: NDArray[np.float64],
    output_axis: NDArray[np.float64],
) -> tuple[list[float | None], list[float | None], list[float | None]]:
    half_span = 0.42
    return _line_coordinates([
        center - half_span * input_axis,
        center + half_span * input_axis,
        None,
        center - half_span * output_axis,
        center + half_span * output_axis,
    ])


def _camera_for_preset(preset: str) -> dict[str, dict[str, float]]:
    presets: Mapping[str, tuple[float, float, float]] = {
        "isometric": (1.45, 1.45, 1.05),
        "top": (0.0, 0.0, 2.25),
        "side": (0.15, -2.15, 0.55),
        "front": (2.15, 0.15, 0.55),
    }
    eye = presets.get(preset, presets["isometric"])
    return {"eye": {"x": eye[0], "y": eye[1], "z": eye[2]}}


def _sample_indices(sample_count: int, frame_count: int) -> NDArray[np.int64]:
    requested = max(12, int(frame_count))
    requested = min(requested, sample_count)
    return np.unique(np.linspace(0, sample_count - 1, requested, dtype=int))


def build_kinematic_3d_figure(
    parameters: core.CardanParameters,
    selected_trajectory: core.KinematicTrajectory,
    current_trajectory: core.KinematicTrajectory,
    optimized_trajectory: core.KinematicTrajectory,
    *,
    labels: ViewerLabels | None = None,
    selected_kind: str = "current",
    frame_count: int = 121,
    frame_duration_ms: int = 45,
    camera_preset: str = "isometric",
) -> Any:
    """Build an animated 3D mechanism with a synchronized speed-ratio chart."""

    if not plotly_available():
        raise RuntimeError("Plotly is required for the interactive 3D viewer.")

    viewer_labels = ViewerLabels() if labels is None else labels
    selected_kind = "optimized" if selected_kind == "optimized" else "current"
    scene = core.calculate_kinematic_scene(parameters, selected_trajectory)
    geometry = scene.geometry
    joint_count = int(parameters.mode)

    figure = make_subplots(
        rows=1,
        cols=2,
        specs=[[{"type": "scene"}, {"type": "xy"}]],
        column_widths=[0.69, 0.31],
        horizontal_spacing=0.035,
    )

    # Fixed shaft centerlines.
    for shaft_index in range(joint_count + 1):
        start = geometry.shaft_points[shaft_index]
        end = geometry.shaft_points[shaft_index + 1]
        figure.add_trace(
            go.Scatter3d(
                x=[start[0], end[0]],
                y=[start[1], end[1]],
                z=[start[2], end[2]],
                mode="lines",
                line={"width": 16, "color": _SHAFT_COLORS[shaft_index % len(_SHAFT_COLORS)]},
                name=f"{viewer_labels.shaft} {shaft_index + 1}",
                hovertemplate=(
                    f"{viewer_labels.shaft} {shaft_index + 1}<br>"
                    "x=%{x:.2f}<br>y=%{y:.2f}<br>z=%{z:.2f}<extra></extra>"
                ),
                showlegend=True,
            ),
            row=1,
            col=1,
        )

    figure.add_trace(
        go.Scatter3d(
            x=geometry.joint_centers[:, 0],
            y=geometry.joint_centers[:, 1],
            z=geometry.joint_centers[:, 2],
            mode="markers+text",
            marker={"size": 6, "color": _JOINT_COLOR},
            text=[f"J{index + 1}" for index in range(joint_count)],
            textposition="top center",
            name=viewer_labels.joint,
            hovertemplate="%{text}<extra></extra>",
        ),
        row=1,
        col=1,
    )

    dynamic_trace_indices: list[int] = []
    initial_frame_index = 0
    for joint_index in range(joint_count):
        center = geometry.joint_centers[joint_index]
        input_direction = geometry.shaft_directions[joint_index]
        output_direction = geometry.shaft_directions[joint_index + 1]
        input_axis = scene.input_yoke_axes[joint_index, initial_frame_index]
        output_axis = scene.output_yoke_axes[joint_index, initial_frame_index]

        x_values, y_values, z_values = _yoke_points(center, input_direction, input_axis, -1.0)
        figure.add_trace(
            go.Scatter3d(
                x=x_values,
                y=y_values,
                z=z_values,
                mode="lines",
                line={"width": 9, "color": _INPUT_YOKE_COLOR},
                name=f"{viewer_labels.input_yoke} J{joint_index + 1}",
                legendgroup=f"joint-{joint_index}",
                hoverinfo="skip",
                showlegend=joint_index == 0,
            ),
            row=1,
            col=1,
        )
        dynamic_trace_indices.append(len(figure.data) - 1)

        x_values, y_values, z_values = _yoke_points(center, output_direction, output_axis, 1.0)
        figure.add_trace(
            go.Scatter3d(
                x=x_values,
                y=y_values,
                z=z_values,
                mode="lines",
                line={"width": 9, "color": _OUTPUT_YOKE_COLOR},
                name=f"{viewer_labels.output_yoke} J{joint_index + 1}",
                legendgroup=f"joint-{joint_index}",
                hoverinfo="skip",
                showlegend=joint_index == 0,
            ),
            row=1,
            col=1,
        )
        dynamic_trace_indices.append(len(figure.data) - 1)

        x_values, y_values, z_values = _cross_points(center, input_axis, output_axis)
        figure.add_trace(
            go.Scatter3d(
                x=x_values,
                y=y_values,
                z=z_values,
                mode="lines+markers",
                line={"width": 11, "color": _CROSS_COLOR},
                marker={"size": 3, "color": _CROSS_COLOR},
                name=f"{viewer_labels.cross} J{joint_index + 1}",
                legendgroup=f"joint-{joint_index}",
                hoverinfo="skip",
                showlegend=joint_index == 0,
            ),
            row=1,
            col=1,
        )
        dynamic_trace_indices.append(len(figure.data) - 1)

    # Synchronized response plot.
    figure.add_trace(
        go.Scatter(
            x=current_trajectory.input_rotation_deg,
            y=current_trajectory.total_speed_ratio,
            mode="lines",
            line={"width": 2.1, "color": _CURRENT_COLOR},
            name=viewer_labels.current,
            hovertemplate="θ=%{x:.1f}°<br>q=%{y:.5f}<extra></extra>",
        ),
        row=1,
        col=2,
    )
    figure.add_trace(
        go.Scatter(
            x=optimized_trajectory.input_rotation_deg,
            y=optimized_trajectory.total_speed_ratio,
            mode="lines",
            line={"width": 2.1, "dash": "dash", "color": _OPTIMIZED_COLOR},
            name=viewer_labels.optimized,
            hovertemplate="θ=%{x:.1f}°<br>q=%{y:.5f}<extra></extra>",
        ),
        row=1,
        col=2,
    )

    marker_index = len(figure.data)
    initial_q = float(selected_trajectory.total_speed_ratio[initial_frame_index])
    initial_theta = float(selected_trajectory.input_rotation_deg[initial_frame_index])
    figure.add_trace(
        go.Scatter(
            x=[initial_theta],
            y=[initial_q],
            mode="markers",
            marker={"size": 11, "color": _SELECTED_COLOR, "line": {"width": 1, "color": "#111827"}},
            name=(viewer_labels.selected_optimized if selected_kind == "optimized" else viewer_labels.selected_current),
            hovertemplate="θ=%{x:.1f}°<br>q=%{y:.5f}<extra></extra>",
            showlegend=True,
        ),
        row=1,
        col=2,
    )

    q_min = float(min(np.min(current_trajectory.total_speed_ratio), np.min(optimized_trajectory.total_speed_ratio)))
    q_max = float(max(np.max(current_trajectory.total_speed_ratio), np.max(optimized_trajectory.total_speed_ratio)))
    q_margin = max(0.02, 0.08 * (q_max - q_min))
    vertical_index = len(figure.data)
    figure.add_trace(
        go.Scatter(
            x=[initial_theta, initial_theta],
            y=[q_min - q_margin, q_max + q_margin],
            mode="lines",
            line={"width": 1.2, "dash": "dot", "color": _SELECTED_COLOR},
            hoverinfo="skip",
            showlegend=False,
        ),
        row=1,
        col=2,
    )

    indices = _sample_indices(selected_trajectory.input_rotation_deg.size, frame_count)
    animation_frames = []
    for display_index, source_index in enumerate(indices):
        frame_data: list[Any] = []
        frame_traces: list[int] = []
        for joint_index in range(joint_count):
            center = geometry.joint_centers[joint_index]
            input_direction = geometry.shaft_directions[joint_index]
            output_direction = geometry.shaft_directions[joint_index + 1]
            input_axis = scene.input_yoke_axes[joint_index, source_index]
            output_axis = scene.output_yoke_axes[joint_index, source_index]

            for coordinates, trace_index in (
                (_yoke_points(center, input_direction, input_axis, -1.0), dynamic_trace_indices[3 * joint_index]),
                (_yoke_points(center, output_direction, output_axis, 1.0), dynamic_trace_indices[3 * joint_index + 1]),
                (_cross_points(center, input_axis, output_axis), dynamic_trace_indices[3 * joint_index + 2]),
            ):
                frame_data.append(go.Scatter3d(x=coordinates[0], y=coordinates[1], z=coordinates[2]))
                frame_traces.append(trace_index)

        theta_value = float(selected_trajectory.input_rotation_deg[source_index])
        q_value = float(selected_trajectory.total_speed_ratio[source_index])
        frame_data.extend([
            go.Scatter(x=[theta_value], y=[q_value]),
            go.Scatter(x=[theta_value, theta_value], y=[q_min - q_margin, q_max + q_margin]),
        ])
        frame_traces.extend([marker_index, vertical_index])
        animation_frames.append(
            go.Frame(
                name=f"frame-{display_index}",
                data=frame_data,
                traces=frame_traces,
                layout=go.Layout(
                    title={
                        "text": (
                            f"{viewer_labels.title} — θ = {theta_value:.1f}°, "
                            f"q = {q_value:.5f}"
                        )
                    }
                ),
            )
        )
    figure.frames = animation_frames

    slider_steps = []
    for display_index, source_index in enumerate(indices):
        angle = float(selected_trajectory.input_rotation_deg[source_index])
        label = f"{angle:.0f}°" if display_index % max(1, len(indices) // 12) == 0 else ""
        slider_steps.append({
            "args": [
                [f"frame-{display_index}"],
                {"frame": {"duration": 0, "redraw": True}, "mode": "immediate", "transition": {"duration": 0}},
            ],
            "label": label,
            "method": "animate",
        })

    scene_points = geometry.shaft_points
    extent_min = scene_points.min(axis=0)
    extent_max = scene_points.max(axis=0)
    span = max(float(np.max(extent_max - extent_min)), 1.0)
    center = 0.5 * (extent_min + extent_max)
    half = 0.58 * span

    figure.update_layout(
        title={
            "text": (
                f"{viewer_labels.title} — "
                f"{viewer_labels.selected_optimized if selected_kind == 'optimized' else viewer_labels.selected_current}"
            ),
            "x": 0.02,
        },
        height=690,
        margin={"l": 0, "r": 0, "t": 70, "b": 30},
        paper_bgcolor="#0E1117",
        plot_bgcolor="#111827",
        font={"color": "#F3F4F6"},
        legend={"orientation": "h", "yanchor": "bottom", "y": 1.01, "xanchor": "right", "x": 1.0},
        scene={
            "xaxis": {"title": "X", "range": [center[0] - half, center[0] + half], "backgroundcolor": "#111827", "gridcolor": "#374151"},
            "yaxis": {"title": "Y", "range": [center[1] - half, center[1] + half], "backgroundcolor": "#111827", "gridcolor": "#374151"},
            "zaxis": {"title": "Z", "range": [-0.58 * span, 0.58 * span], "backgroundcolor": "#111827", "gridcolor": "#374151"},
            "aspectmode": "cube",
            "camera": _camera_for_preset(camera_preset),
        },
        xaxis2={
            "title": viewer_labels.input_angle,
            "range": [0.0, 360.0],
            "gridcolor": "#374151",
            "zerolinecolor": "#6B7280",
        },
        yaxis2={
            "title": viewer_labels.speed_ratio,
            "range": [q_min - q_margin, q_max + q_margin],
            "gridcolor": "#374151",
            "zerolinecolor": "#6B7280",
        },
        updatemenus=[{
            "type": "buttons",
            "direction": "left",
            "x": 0.02,
            "y": -0.06,
            "showactive": False,
            "buttons": [
                {
                    "label": viewer_labels.play,
                    "method": "animate",
                    "args": [
                        None,
                        {
                            "frame": {"duration": int(frame_duration_ms), "redraw": True},
                            "fromcurrent": True,
                            "transition": {"duration": 0},
                        },
                    ],
                },
                {
                    "label": viewer_labels.pause,
                    "method": "animate",
                    "args": [
                        [None],
                        {
                            "frame": {"duration": 0, "redraw": False},
                            "mode": "immediate",
                            "transition": {"duration": 0},
                        },
                    ],
                },
            ],
        }],
        sliders=[{
            "active": 0,
            "currentvalue": {"prefix": "θ = ", "suffix": ""},
            "pad": {"t": 35},
            "steps": slider_steps,
            "x": 0.17,
            "len": 0.80,
            "y": -0.045,
        }],
        annotations=[{
            "text": viewer_labels.schematic_note,
            "xref": "paper",
            "yref": "paper",
            "x": 0.01,
            "y": -0.15,
            "showarrow": False,
            "font": {"size": 11, "color": "#AEB6C2"},
        }],
    )
    return figure
